# Generated by Django 4.2.1 on 2023-06-11 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import socialhive.common.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, validators=[socialhive.common.utils.validators.alphanumeric_with_special_characters])),
                ('url', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=200)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
