# Generated by Django 4.2.1 on 2023-06-11 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(help_text='Post content', max_length=200, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters, spaces, and specific special characters are allowed.', regex='^[a-zA-Z0-9\\s!@#$%^&*()\\[\\]_\\-=:"\\\']+')]),
        ),
    ]
