# Generated by Django 4.2.1 on 2023-06-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_historicalhiveuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhiveuser',
            name='password',
            field=models.CharField(max_length=265),
        ),
        migrations.AlterField(
            model_name='hiveuser',
            name='password',
            field=models.CharField(max_length=265),
        ),
    ]
